org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
net.minecraftforge.gradle.merge-source-sets=true

minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.22)
forge_version=61.2.0
forge_version_range=[61,)
loader_version_range=[61,)
mapping_channel=official
mapping_version=1.21.11

mod_id=quickslot
mod_name=QuickSlot
mod_license=All Rights Reserved
mod_version=1.5.0
mod_group_id=dev.netrox.quickslot
mod_authors=netrox336-ops
mod_description=QuickSlot автоматически поддерживает порядок в хотбаре, управляет пополнением и выбором блоков, улучшает снаряжение и показывает состояние в настраиваемом HUD.
