name: Сборка QuickSlot

on:
  push:
    branches: [main, "release/**"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Получение исходников
        uses: actions/checkout@v5

      - name: Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.6.0'

      - name: Сборка
        run: gradle build --stacktrace

      - name: Готовый мод
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: quickslot-1.0.0-minecraft-1.21.11
          path: build/libs/*.jar
          if-no-files-found: error
